(function () {
"use strict";
const C=(id,title,questions)=>({id,title,questions});
window.SNABBFRAGOR.push(
C("4.1","Flexbox för rader, menyer och kort",[
["När passar flexbox bäst?","För endimensionella layouter där innehåll ordnas i en rad eller kolumn.","display: flex;"],["Vad gör flex-direction?","Den anger huvudaxelns riktning, exempelvis row eller column.","flex-direction: column;"],["Vad gör justify-content?","Den fördelar utrymme och placerar objekt längs huvudaxeln.","justify-content: space-between;"],["Vad gör align-items?","Den placerar flexobjekt längs tväraxeln.","align-items: center;"],["Varför används flex-wrap?","Den låter objekt brytas till nya rader när utrymmet inte räcker.","flex-wrap: wrap;"]]),
C("4.2","Grid för sidlayouter",[
["När passar CSS Grid bäst?","När layouten behöver styras i både rader och kolumner.","display: grid;"],["Hur skapar du tre lika breda kolumner?","Använd grid-template-columns med tre fr-enheter.","grid-template-columns: repeat(3, 1fr);"],["Vad gör gap?","Det skapar mellanrum mellan gridens rader och kolumner.","gap: 1rem;"],["Vad gör minmax()?","Den anger ett minsta och största mått för ett gridspår.","minmax(16rem, 1fr)"],["Vad gör auto-fit i en responsiv grid?","Den skapar så många kolumner som ryms och låter tomma spår falla ihop.","repeat(auto-fit, minmax(16rem, 1fr))"]]),
C("4.3","Responsiva mått och bilder",[
["Vad är skillnaden mellan px och rem?","px är ett fast CSS-mått medan rem utgår från sidans grundtextstorlek.","padding: 2rem;"],["Varför används max-width i ch för brödtext?","Det begränsar radlängden utifrån ungefärlig teckenbredd och förbättrar läsbarheten.","max-width: 70ch;"],["Vad gör clamp()?","Den ger ett responsivt värde med minimi-, önskat och maximivärde.","font-size: clamp(1.5rem, 4vw, 3rem);"],["Hur hindrar du en bild från att bli bredare än sin behållare?","Sätt max-width till 100 procent och height till auto.","img { max-width: 100%; height: auto; }"],["Varför är relativa mått användbara?","De kan anpassa sig till textstorlek, behållare eller viewport.","width: 80%;"]]),
C("4.4","Media queries",[
["Vilken viewport-rad behövs för responsiv mobilvisning?","En meta-tagg som gör viewportens bredd lika med enhetens bredd.","<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"],["Vad betyder mobile first?","Grundstilen skrivs för små skärmar och byggs ut för större skärmar.","@media (min-width: 48rem) { ... }"],["När bör en brytpunkt läggas till?","När innehållet eller layouten behöver ändras, inte för en viss enhetsmodell.",""],["Vad gör en media query?","Den tillämpar CSS bara när ett angivet villkor är uppfyllt.","@media (min-width: 48rem) { ... }"],["Hur bör en responsiv navigation testas?","Ändra viewportens bredd och kontrollera även tangentbord och fokus.",""]]),
C("4.5","Miniuppgift: responsiv startsida",[
["Vad är målet med den responsiva startsidan?","Att innehåll och layout ska fungera på mobil, surfplatta och dator.",""],["Vilka två layoutverktyg ska användas?","Flexbox och/eller CSS Grid där de passar sidans delar.","display: grid;"],["Hur görs kort responsiva utan många brytpunkter?","Använd en grid med auto-fit och minmax.","repeat(auto-fit, minmax(16rem, 1fr))"],["Vilken arbetsordning är lämplig?","Planera HTML-strukturen, bygg mobile first och lägg sedan till större layouter.","struktur → mobil → större vyer"],["Vad ska självkontrollen omfatta?","Olika bredder, bilder, länkar, fokus, läsbarhet och validering.",""]]),
C("4.6","Använda SQLite-databaser",[
["Vad är SQLite?","En lätt relationsdatabas som lagras i en lokal fil.","import sqlite3"],["Hur öppnas en anslutning i Python?","Med sqlite3.connect och databasfilens namn.","conn = sqlite3.connect(\"recept.db\")"],["Vad gör CREATE TABLE?","Det skapar en tabell med angivna kolumner och datatyper.","CREATE TABLE recipes (...)"],["Varför används parametrar i SQL-frågor?","De hanterar värden säkrare än att bygga SQL med strängkonkatenering.","cursor.execute(\"INSERT INTO recipes VALUES (?)\", (name,))"],["Varför behövs commit()?","Det sparar ändringar som INSERT, UPDATE och DELETE i databasen.","conn.commit()"]]),
C("4.7","Miniuppgift: använda SQLite-databaser",[
["Varför delas programmet i databas.py och main.py?","Databaslogik skiljs från meny och användarflöde.","databas.py\nmain.py"],["Vad bör databasmodulen ansvara för?","Anslutning, tabellskapande och funktioner som läser eller ändrar data.",""],["Vad bör huvudfilen ansvara för?","Menyn, användarens val och anrop till databasfunktionerna.",""],["Hur testar du databaskoden metodiskt?","Prova skapa, lägga till, läsa, ändra och ta bort med kontrollerade testdata.","CRUD"],["Varför ska anslutningen stängas?","För att frigöra resurser och avsluta databasarbetet korrekt.","conn.close()"]]),
C("5.1","Vad JavaScript tillför",[
["Vad tillför JavaScript till en webbsida?","Beteende och interaktion som kan reagera på användaren och ändra sidan.",""],["Hur kopplas en extern JavaScript-fil?","Med ett script-element vars src pekar på filen.","<script src=\"app.js\"></script>"],["Vad används webbläsarens Console till?","Att se fel, varningar och utskrifter från JavaScript.","console.log(\"Skriptet körs\");"],["Varför bör du börja med små synliga förändringar?","Då märker du snabbt om skriptet körs och var ett fel uppstår.",""],["Vad gör strict mode?","Det aktiverar striktare regler och hjälper till att upptäcka vissa kodfel.","\"use strict\";"]]),
C("5.2","Hämta och ändra element",[
["Hur hittar querySelector ett element?","Den använder en CSS-selektor och returnerar det första matchande elementet.","document.querySelector(\".message\")"],["Hur ändras ett elements text säkert?","Sätt elementets textContent.","message.textContent = \"Klart!\";"],["Hur lyssnar du på ett knappklick?","Lägg till en click-lyssnare med addEventListener.","button.addEventListener(\"click\", handler);"],["Vad gör classList.toggle?","Den lägger till en klass om den saknas och tar bort den om den finns.","menu.classList.toggle(\"is-open\");"],["Varför kan CSS-kunskaper hjälpa med DOM?","Samma selektorer kan ofta användas för att hitta element i JavaScript.",""]]),
C("5.3","Formulär och feedback",[
["Vilket event ska normalt fånga formulärinlämning?","Formulärets submit-event.","form.addEventListener(\"submit\", handler);"],["Varför används preventDefault i ett övningsformulär?","Det hindrar sidans vanliga omladdning så att JavaScript kan hantera flödet.","event.preventDefault();"],["Hur läses värdet från ett inputfält?","Via fältets value-egenskap.","const name = input.value;"],["Varför är submit bättre än bara knappens click?","Submit fångar även inlämning med Enter i ett formulärfält.",""],["Vad kännetecknar bra feedback?","Den är tydlig, nära händelsen och berättar vad som hände eller behöver rättas.",""]]),
C("5.4","Små interaktioner utan ramverk",[
["Vilket grundmönster återkommer i små interaktioner?","Hitta element, lyssna på event och ändra något synligt.",""],["Hur kan en meny visas och döljas?","Växla en CSS-klass när menyknappen aktiveras.","menu.classList.toggle(\"is-open\");"],["Vad är ARIA?","Attribut och roller som kan förmedla gränssnittets betydelse och tillstånd till hjälpmedel.","aria-expanded=\"false\""],["Vad ska aria-expanded visa?","Om innehållet som en kontroll styr är öppet eller stängt.","button.setAttribute(\"aria-expanded\", \"true\")"],["När räcker vanlig JavaScript utan ramverk?","När interaktionen är liten och kan byggas tydligt med DOM och events.",""]]),
C("5.5","Miniuppgift: interaktiv komponent",[
["Vad kännetecknar en bra liten komponent?","Den gör en sak tydligt och har begripliga lägen och kontroller.",""],["Vilka tre steg behövs i JavaScript-delen?","Välj element, lyssna på en händelse och uppdatera komponentens läge.",""],["Var bör utseendet för öppet eller aktivt läge ligga?","I en CSS-klass som JavaScript växlar.",".is-open { display: block; }"],["Vad ska tangentbordstestet kontrollera?","Att kontroller kan nås, aktiveras och visar tydligt fokus.",""],["Varför ska grundläget fungera innan fler funktioner läggs till?","Det gör komponenten enklare att felsöka och bedöma.",""]]),
C("5.6","Miniuppgift: kombinera GUI, API och databas",[
["Vilka tre delar kombineras i skämtregistret?","Ett grafiskt gränssnitt, ett API och en databas.","GUI → API → databas"],["Vad gör API-anropet?","Det hämtar data från en extern tjänst som programmet kan visa eller spara.",""],["Varför sparas data i en databas?","Så att poster finns kvar och kan sökas eller visas senare.",""],["Varför bör API-, databas- och GUI-kod delas upp?","Varje del får ett tydligt ansvar och blir lättare att testa och byta ut.",""],["Vad bör testas om API:t inte svarar?","Att programmet fångar felet och visar ett begripligt meddelande utan att krascha.",""]]),
C("6.1","Bildformat på webben",[
["Vad är skillnaden mellan pixel- och vektorbilder?","Pixelbilder består av bildpunkter; vektorbilder beskrivs med former och kan skalas utan pixlighet.",""],["När passar JPEG?","För fotografier där liten filstorlek är viktig och transparens inte behövs.","photo.jpg"],["När passar PNG?","När förlustfri kvalitet eller transparens behövs, exempelvis enkel grafik.","logo.png"],["När passar SVG?","För logotyper, ikoner och annan skalbar vektorgrafik.","icon.svg"],["Vad är en fördel med WebP eller AVIF?","De kan ge hög kvalitet med mindre filstorlek än äldre format.","image.webp"]]),
C("6.2","Optimera bilder",[
["Varför ska en bild ha rätt pixelmått före publicering?","En onödigt stor bild tar längre tid och mer data att ladda.",""],["Vad innebär bildkomprimering?","Att minska filstorleken, ibland genom att kasta information som ögat knappt märker.",""],["Vad gör loading=\"lazy\"?","Det skjuter upp laddning av bilder utanför den synliga delen av sidan.","<img loading=\"lazy\" ...>"],["Vad gör srcset?","Det erbjuder flera bildfiler så webbläsaren kan välja lämplig storlek.","srcset=\"small.webp 400w, large.webp 1200w\""],["Hur kontrollerar du bildladdningen?","Använd Network-panelen och granska storlek, format och när filerna hämtas.",""]]),
C("6.3","Ljud, video och inbäddat innehåll",[
["Hur ger du användaren uppspelningskontroller?","Lägg till attributet controls på audio eller video.","<video controls>...</video>"],["Varför kan flera source-element användas?","Webbläsaren kan välja ett mediaformat som den stöder.","<source src=\"film.webm\" type=\"video/webm\">"],["Vad bör video erbjuda för användare som inte hör ljudet?","Textning med track och vid behov en textversion.","<track kind=\"captions\" ...>"],["Vad är ett iframe-element?","Ett element som bäddar in innehåll från en annan webbsida eller tjänst.","<iframe title=\"Karta\" ...></iframe>"],["Varför bör media inte starta oväntat?","Autouppspelning kan störa och användaren ska kunna styra uppspelningen.",""]]),
C("6.4","Prestanda och enkel felsökning",[
["Vad visar Network-panelen?","Vilka resurser som begärs, deras status, storlek och laddningstid.","404 Not Found"],["Hur hittar du en saknad fil?","Leta efter ett misslyckat anrop och kontrollera sökväg och filnamn.",""],["Varför testar man ibland utan cache?","För att säkerställa att aktuella filer verkligen hämtas från servern.","Disable cache"],["Vad används Lighthouse till?","En automatisk granskning av bland annat prestanda, tillgänglighet och god praxis.",""],["I vilken ordning bör du felsöka?","Återskapa felet, läs Console och Network, kontrollera orsaken och testa en ändring i taget.",""]]),
C("7.1","Tillgänglighetens fyra principer",[
["Vilka är WCAG:s fyra principer?","Möjlig att uppfatta, hanterbar, begriplig och robust.","POUR"],["Vad betyder möjlig att uppfatta?","Information måste kunna uppfattas på fler sätt, exempelvis med textalternativ.","alt=\"...\""],["Vad betyder hanterbar?","Gränssnittet ska kunna användas, bland annat med tangentbord.",""],["Vad betyder begriplig?","Innehåll och funktioner ska vara tydliga och förutsägbara.",""],["Vad betyder robust?","Innehållet ska fungera med olika webbläsare och hjälpmedel.",""]]),
C("7.2","Färg, kontrast och navigering",[
["Varför får färg inte vara den enda informationsbäraren?","Alla uppfattar inte färg på samma sätt; komplettera med text, symbol eller form.",""],["Vad är färgkontrast?","Skillnaden i ljushet mellan exempelvis text och bakgrund.",""],["Varför behövs synlig tangentbordsfokus?","Användaren måste se vilken länk eller kontroll som är aktiv.",":focus-visible { outline: 3px solid; }"],["Vad bör navigationens länkar ha?","Tydliga namn, logisk ordning och fungerande fokusläge.",""],["Varför kan mättad röd text vara svårläst?","Stark färg och otillräcklig kontrast kan skapa visuella störningar.",""]]),
C("7.3","GDPR och personuppgifter på webben",[
["Vad är en personuppgift?","Information som direkt eller indirekt kan kopplas till en levande person.",""],["Vad innebär uppgiftsminimering?","Samla bara in de personuppgifter som verkligen behövs.",""],["Vad är en rättslig grund?","Ett lagligt stöd som krävs för att behandla personuppgifter.",""],["Vad måste användaren informeras om?","Vilka uppgifter som samlas in, varför, hur länge och vem som ansvarar.",""],["Varför måste externa tjänster granskas?","De kan själva samla in eller överföra personuppgifter.",""]]),
C("7.4","Upphovsrätt och Creative Commons",[
["Vad innebär upphovsrätt?","Skaparen får automatiskt rättigheter till sitt verk.",""],["Vad är skillnaden mellan äganderätt och upphovsrätt?","Att äga ett exemplar betyder inte att du får kopiera eller publicera verket.",""],["Vad är Creative Commons?","Standardiserade licenser där skaparen anger hur ett verk får användas.","CC BY"],["Vad betyder BY i en CC-licens?","Att upphovspersonen ska anges.",""],["Vad bör en källangivelse innehålla?","Verkets titel, upphovsperson, källa och licens.",""]]),
C("7.5","Etiska designval",[
["Vad är ett mörkt mönster?","Design som manipulerar användaren till ett val som främst gynnar tjänsten.",""],["Vad kännetecknar ansvarsfull design?","Tydliga val, ärlig information och respekt för användarens kontroll och integritet.",""],["Varför ska språk och ton anpassas?","Olika målgrupper behöver begripliga ord och en inkluderande ton.",""],["Hur påverkar filstorlek etik och tillgänglighet?","Tunga sidor kostar data, laddar långsamt och utestänger användare med svag uppkoppling.",""],["Varför bör automatiska funktioner granskas?","De kan ge olämpliga resultat eller skada människor om sammanhang och konsekvenser missas.",""]]),
C("7.6","Planera en webbplats",[
["Varför börjar planeringen med syfte och målgrupp?","De styr innehåll, språk, funktioner och layout.",""],["Vad är en sitemap?","En översikt över webbplatsens sidor och hur de hänger ihop.","startsida → undersidor"],["Vad är en wireframe?","En enkel skiss över sidans struktur och placering av innehåll.",""],["Varför bör innehåll planeras före visuella detaljer?","Designen ska stödja verkligt innehåll och användarens mål.",""],["Varför ska andra personer testa webbplatsen?","De kan upptäcka oklarheter som skaparen själv har vant sig vid.",""]]),
C("7.7","Testa i webbläsaren",[
["Vad används responsivt läge till?","Att simulera olika viewportbredder och upptäcka layoutproblem.",""],["Vad används Console till vid testning?","Att hitta JavaScript-fel och egna diagnostiska utskrifter.",""],["Vad används Network till vid testning?","Att se misslyckade, långsamma eller onödigt stora resursanrop.",""],["Hur testar du tangentbordsanvändning?","Tabba genom sidan och kontrollera ordning, fokus och aktivering.","Tab → Enter"],["Vad bör en snabb testchecklista omfatta?","Länkar, formulär, flera bredder, tangentbord, media, Console och Network.",""]]),
C("8.3","Inlämning 1: Figma",[
["Vad är huvudsyftet med Figma-inlämningen?","Att planera hotellwebbplatsens visuella design innan den kodas.",""],["Vad ska designen visa?","Sidornas struktur, innehåll, typografi, färger och viktiga komponenter.",""],["Vad är skillnaden mellan en design och färdig HTML?","Designen visar den planerade lösningen; HTML och CSS genomför den i webbläsaren.",""],["Vad bör kontrolleras före inlämning?","Att alla efterfrågade vyer och nivåkrav finns och att delningslänken fungerar.",""],["Hur delas Figma-arbetet?","Med en länk vars behörighet låter läraren öppna designen.",""]]),
C("8.4","Inlämning 2: Hotellwebbplatsen",[
["Vilka två länkar ska lämnas in?","Länken till GitHub Pages och länken till repositoryt med koden.",""],["Varför behövs både publicerad sida och repository?","Den ena visar resultatet och den andra visar kod och filstruktur.",""],["Vad ska testas före inlämning?","Responsivitet, länkar, bilder, formulär, tillgänglighet och att inga konsolfel finns.",""],["Hur påverkar nivåkraven arbetet?","Högre nivå kräver mer genomarbetad funktion, design, kodkvalitet och motivering.",""],["Vilket vanligt publiceringsfel bör kontrolleras?","Att filnamn och relativa sökvägar matchar exakt på GitHub Pages.",""]]),
C("8.5","Inlämning 3: Utvärdering",[
["Vad är syftet med utvärderingen?","Att analysera arbetsprocessen, resultatet och vad som kan förbättras.",""],["Var ska utvärderingen skrivas?","I ett Google Drive-dokument med tydliga rubriker.",""],["Vad gör ett exempel konkret?","Det hänvisar till ett faktiskt val, problem eller kodstycke och förklarar konsekvensen.",""],["Vad skiljer analys från en enkel beskrivning?","Analysen förklarar varför något hände och hur val påverkade resultatet.",""],["Vad bör förbättringsförslagen innehålla?","Konkreta nästa steg kopplade till webbplatsen eller arbetsprocessen.",""]]),
C("9.1","HTML-referenser",[
["Vad används en HTML-referens till?","För att skriva tecken som annars har särskild betydelse eller är svåra att skriva direkt.","&lt; → <"],["Hur skrivs ett mindre än-tecken som referens?","Med den namngivna referensen &lt;.","&lt;"],["Hur skrivs ett större än-tecken som referens?","Med den namngivna referensen &gt;.","&gt;"],["Hur skrivs ett et-tecken som referens?","Med &amp; så att tecknet inte inleder en ny referens.","&amp;"],["Vad är skillnaden mellan namngiven och numerisk referens?","Den ena använder ett namn och den andra tecknets nummer.","&copy; eller &#169;"]]),
C("9.2","HTML-forum",[
["Varför kan utvecklarforum vara användbara?","Du kan hitta förklaringar och lösningar på problem som andra redan mött.",""],["Vad bör du kontrollera i ett gammalt forumsvar?","Datum, sammanhang och om lösningen fortfarande följer aktuella standarder.",""],["Varför ska kod från forum inte kopieras blint?","Den kan vara fel, osäker eller inte passa ditt problem.",""],["Hur formulerar du en bra teknisk fråga?","Visa målet, relevant kod, felmeddelandet och vad du redan har provat.",""],["Vilken källa bör bekräfta ett forumsvar?","Aktuell dokumentation eller en tillförlitlig referens, exempelvis MDN.",""]]),
C("9.3","AI och LLMer",[
["Vad är en stor språkmodell?","En modell tränad att bearbeta och generera språk utifrån mönster i data.",""],["Hur kan AI hjälpa vid webbutveckling?","Med förklaringar, idéer, kodförslag och felsökningsstöd.",""],["Varför måste AI-genererad kod granskas?","Den kan innehålla sakfel, säkerhetsproblem eller kod som inte passar uppgiften.",""],["Vad bör en bra prompt innehålla?","Mål, relevant sammanhang, krav och önskat format.",""],["Vilken information bör inte delas utan eftertanke?","Personuppgifter, lösenord, API-nycklar och annat känsligt material.",""]]),
C("10.1","Tre sätt att lägga till CSS-deklarationer",[
["Vilka tre sätt finns att lägga till CSS?","Extern fil, style-element i head och inline via style-attribut.",""],["Hur kopplas extern CSS?","Med ett link-element i head.","<link rel=\"stylesheet\" href=\"styles.css\">"],["När kan ett style-element passa?","Vid små, avgränsade tester eller en enskild sida.","<style>p { color: blue; }</style>"],["Var skrivs inline-CSS?","I ett elements style-attribut.","<p style=\"color: blue\">Text</p>"],["Varför föredras extern CSS i projekt?","Struktur och presentation hålls isär och samma stilmall kan återanvändas.",""]]),
C("10.2","Vanliga CSS-egenskaper",[
["Vad styr color och background-color?","Textens färg respektive elementets bakgrundsfärg.","color: #222; background-color: #fff;"],["Vad är en font stack?","En prioriterad lista med typsnitt och en generell reservfamilj.","font-family: Arial, Helvetica, sans-serif;"],["Vad gör text-align?","Det justerar inlineinnehåll horisontellt i sin behållare.","text-align: center;"],["Hur gör du en bild responsiv?","Använd max-width 100 procent och automatisk höjd.","max-width: 100%; height: auto;"],["Vad gör object-fit?","Det styr hur media anpassas inom en ruta med bestämda mått.","object-fit: cover;"]]),
C("10.3","Boxmodellen",[
["Vilka delar ingår i boxmodellen?","Content, padding, border och margin.",""],["Vad är padding?","Luft mellan innehållet och kantlinjen.","padding: 1rem;"],["Vad är margin?","Avstånd utanför elementets kantlinje.","margin: 1rem;"],["Vad omsluter border?","Elementets content och padding.","border: 1px solid;"],["Hur påverkar content-box angiven width?","Padding och border läggs ovanpå den angivna innehållsbredden.",""]]),
C("10.4","Block och inline",[
["Hur beter sig ett blockelement normalt?","Det börjar på en ny rad och tar tillgänglig bredd.","display: block;"],["Hur beter sig ett inline-element normalt?","Det följer textflödet och tar bara den bredd innehållet behöver.","display: inline;"],["Ge exempel på ett blockelement.","p, div och h1 är vanliga blockelement.","<p>Text</p>"],["Ge exempel på ett inline-element.","a, strong och span är vanliga inline-element.","<span>Text</span>"],["När passar inline-block?","När element ska ligga i textflödet men ändå kunna få tydlig bredd och höjd.","display: inline-block;"]]),
C("10.5","div och span",[
["Vad är div?","En generell blockbehållare utan egen semantisk betydelse.","<div class=\"card\">...</div>"],["Vad är span?","En generell inlinebehållare för en mindre del av text eller innehåll.","<span class=\"price\">99 kr</span>"],["När bör ett semantiskt element väljas före div?","När innehållet har en tydlig roll som nav, main, article eller footer.",""],["Varför används class ofta på div och span?","För att välja och återanvända styling eller beteende.",".price { font-weight: bold; }"],["Vad är skillnaden mellan div och span i standardläget?","div är block och span är inline.",""]]),
C("10.6","CSS reset och normalize",[
["Varför används en CSS-reset?","För att minska oönskade skillnader i webbläsarnas standardstilar.",""],["Vad gör box-sizing: border-box?","Padding och border räknas in i elementets angivna bredd.","*, *::before, *::after { box-sizing: border-box; }"],["Varför sätts body margin ofta till 0?","För att ta bort webbläsarens standardmarginal runt sidan.","body { margin: 0; }"],["Varför används display: block på bilder?","Det tar bort inline-bildens utrymme mot textraden och gör layouten enklare.","img { display: block; }"],["Vad är skillnaden mellan reset och normalize?","Reset tar bort många standardstilar; normalize jämnar ut skillnader men bevarar fler användbara standarder.",""]]),
C("10.7","Olika typer av selektorer",[
["Vad väljer universalselektorn?","Alla element inom sitt omfång.","* { box-sizing: border-box; }"],["Vad väljer en typselektor?","Alla element av en viss HTML-typ.","p { line-height: 1.5; }"],["Hur skrivs klass- och id-selektorer?","Klass skrivs med punkt och id med nummertecken.",".card { }\n#menu { }"],["Vad gör en gruppselektor?","Den ger samma deklarationer till flera selektorer.","h1, h2, h3 { line-height: 1.2; }"],["Vad väljer en härstammande selektor?","Element som ligger inuti ett angivet föräldrasammanhang.","article p { max-width: 70ch; }"]])
);
}());
